### ISSUE TITLE
Language naming conflicts

### ISSUE THREAD

**Issue by TartaricAcid** [TheMarstonConnell/randomlootmod#1]
random loot mod's I18n don't have namespaced, and have some conflicts with other mods 
>  `itemGroup.modTab`
> dmonsters: `Deadly Monsters`
> randomloot: `Random Loot Mod`

I think the forge doc can help your: <https://mcforge.readthedocs.io/en/latest/concepts/internationalization/#usage-with-blocks-and-items>

And I submit the same issues in https://github.com/bigbang87/deadly-monsters/issues/24

**Comment by TheMarstonConnell** [comment]
Fixed in update 1.3.1
