### ISSUE TITLE
Mining Speed changes and is not consistent

### ISSUE THREAD

**Issue by Tyranuss** [TheMarstonConnell/randomlootmod#10]
Hello.

I'm playing RAD modpack with your mod and using a pickaxe which constantly changes the mining speed. Sometimes is showing its real speed 18.00 but either upon leveling or relogin the mining speed drops to 0.83 or sometimes even to 0.00.
Is there a way to fix this in config files or?
Cheers

**Comment by Tyranuss** [comment]
I was in a hurry so I didn't provide any details:
This is occurring in RAD versions 1.19, 1.20 and 1.20a. 
The pickaxe speed was 15.00 (I believe) without enchantments,
I enchanted it with Efficiency V, Unbreaking III, Fortune III and Mending.
It is possible that Efficiency enchant messed something up, but I don't believe it, because before I enchanted it I already had couple of levels, meaning it was changing before the added enchants. 

I'm not sure if you need more details, but if I can help do ask.

**Comment by TheMarstonConnell** [comment]
Solved in the 1.13 release. Currently in alpha.
