### ISSUE TITLE
Server Log being Spamming with "Making <player> float when they have Ancient Briefs on

### ISSUE THREAD

**Issue by emibanana** [TheMarstonConnell/randomlootmod#101]
https://cdn.discordapp.com/attachments/1031541706388152430/1053550227715526677/Screenshot_3.png

https://cdn.discordapp.com/attachments/1031541706388152430/1053549552688451704/image.png

this is literally so retarded, please fix ASAP

**Comment by emibanana** [comment]
@TheMarstonConnell

**Comment by TheMarstonConnell** [comment]
Yeah maybe don't use language like that. Mod isn't being maintained by me currently
