### ISSUE TITLE
Soft Crash In New Version

### ISSUE THREAD

**Issue by subsevenx** [TheMarstonConnell/randomlootmod#18]
Hi! 

I really like this mod! Been playing with it a lot. With that said, I ran into a soft crash with the new version.

**What I Did**: Opened a new case 
**What I expected**: An item
**What I Got**: A [crash](https://paste.dimdev.org/evutelasic.mccrash)

I should mention I did change the config with the new update. I lowered the actual chance of getting an item to 50, instead of the default 100. 

Thank you for your time!

**Comment by TheMarstonConnell** [comment]
I'm sorry I forget when this was made, what version were you using and does it still happen in the new version?
