### ISSUE TITLE
[1.1] Mod references EntityPlayerSP server-side

### ISSUE THREAD

**Issue by robmart** [TheMarstonConnell/randomlootmod#2]
https://gist.github.com/robmart/ac9731b7e8685dd589b4dbfe08f2fa6d

As the title says, the mod attempts to use EntityPlayerSP server-side which crashes the game.

**Comment by TheMarstonConnell** [comment]
What did you do that made it crash?

**Comment by TheMarstonConnell** [comment]
I figured it is when the mod is used on a server, I think I have fixed this, if it continues feel free to reopen this issue.
