### ISSUE TITLE
[Request] Case Opener

### ISSUE THREAD

**Issue by Andronomos** [TheMarstonConnell/randomlootmod#21]
I would love to see a block added that can automatically open cases for you. Similar to the loot bag opener from the LootBags mod.

This would be a huge QoL improvement for me because when I get my mob farm set up I can easily get a thousand or more cases in an hour. Opening them by hand 1 by 1 can get a bit tedious especially when you have to open quite a few to get the tool you're looking for.

**Comment by TheMarstonConnell** [comment]
Currently added in version 1.7.1 (not currently available on curseforge)
