### ISSUE TITLE
Auto repair station repairs non-repairable items...

### ISSUE THREAD

**Issue by spdkils** [TheMarstonConnell/randomlootmod#23]
Doesn't check the repairable flag before repairing.

Also if you leave screen and come back it creates a lot of glitch item scenario in your hands. Phantom items, etc.

**Comment by TheMarstonConnell** [comment]
Well see a big problem with this is that my items have the is repairable flag off because then you can repair the items in an anvil which I didn't want.

Also what does that mean 'leave screen'

**Comment by TheMarstonConnell** [comment]
Fixed in 1.7.4
