### ISSUE TITLE
Reforge with Golden Anvil stack traits instead of resetting

### ISSUE THREAD

**Issue by Aranoxx** [TheMarstonConnell/randomlootmod#24]
Using the Golden Anvil reset the main value eg. mining value, but the previous trait is left and a new trait added. So basicly the reforge can make an item with all traits on.

**Comment by TheMarstonConnell** [comment]
which version of the mod are you using?

**Comment by Ghosttoast12345** [comment]
I'm still having this bug on the latest version and after you get all the traits it crashes. Kinda sucks but oh well.

**Comment by kafeinnet** [comment]
Hi, I'm having the same issue with version 1.7.1 (Roguelike, Aventures and Dungeon modpack).

**Comment by TheMarstonConnell** [comment]
Fixed in 1.7.4
