### ISSUE TITLE
[1.7.1] Server crash

### ISSUE THREAD

**Issue by Theray070696** [TheMarstonConnell/randomlootmod#25]
Upon trying to boot the server, it crashes.

Crash log: https://pastebin.com/38VhFmFF
Full log: https://pastebin.com/MKBTzPXk

**Comment by TheMarstonConnell** [comment]
Ah shoot, I'll get that fixed that should be a client only call

**Comment by TheMarstonConnell** [comment]
okay I fixed it, it'll come out in an update soon. (1.7.3)
