### ISSUE TITLE
server crashes at startup when using versions 1.7.1 or 1.7.2 

### ISSUE THREAD

**Issue by bessiq** [TheMarstonConnell/randomlootmod#26]
Hi,

When using Random Loot Mod 1.7.1 or 1.7.2, Forge _server_ (2847) crashes during initialization. If I use RLM version 1.7, the server starts up properly. I did delete the config and allowed the new versions to re-create it. And the issue doesn't occur on a local Forge (2847) profile with identical mods and configs. 

Here's a paste of a hopefully relevant part of my debug log:
[https://pastebin.com/idzdvsUd](url)

Let me know if it's some conflict or error on my end, or if you want any other logs or details. And thanks for making such a cool mod!

**Comment by TheMarstonConnell** [comment]
It'll be fixed in 1.7.3 (already on github)

**Comment by bessiq** [comment]
Awesome, thanks for the update.

**Comment by TheMarstonConnell** [comment]
Fixed in 1.7.3
