### ISSUE TITLE
Ticking Entity: Crash for armor

### ISSUE THREAD

**Issue by Lordbaane** [TheMarstonConnell/randomlootmod#28]
https://paste.dimdev.org/anegowagok.mccrash

Ran up to a newly spawned mob and as soon as I hit it the game crashed. Said it might be a conflict with loot slash conquer. Maybe similar to other crash opened 4 days ago.

**Comment by TheMarstonConnell** [comment]
I just overlooked that mobs could wear armor, it's on github but not compiled yet

**Comment by TheMarstonConnell** [comment]
Fixed in 1.7.4
