### ISSUE TITLE
Weapon/tool name bug

### ISSUE THREAD

**Issue by SparrowGenji9T8** [TheMarstonConnell/randomlootmod#29]
Each time i get a Weapon or a tool and when i hit an enemy or mine something the name becomes like Random Sword, Random Axe and so on, can you please fix it?

**Comment by TheMarstonConnell** [comment]
I am unable to reproduce this bug, what version were you using?

**Comment by SparrowGenji9T8** [comment]
I was using the latest at the time when i got the bug
