### ISSUE TITLE
Getting server side error with Random Loot 1.2

### ISSUE THREAD

**Issue by EzekielZenkaiyo** [TheMarstonConnell/randomlootmod#3]
[crash-2018-09-17_09.57.52-server.txt](https://github.com/TheMarstonConnell/randomlootmod/files/2388831/crash-2018-09-17_09.57.52-server.txt)

Trying to run Random Loot 1.2 on a server and getting an error.
Basically using some client class that doesn't exist on server side if I understand i well. See attached file for detail..

It is running very well as Single player and it is also running if I open LAN, but then things get slowed a lot, having some rubber banding and all even if I'm still the only player.

Hope this help.

**Comment by TheMarstonConnell** [comment]
It is now fixed in the update 1.3.1
