### ISSUE TITLE
Golden anvil issue - not enough blaze powder

### ISSUE THREAD

**Issue by Goldy93** [TheMarstonConnell/randomlootmod#32]
1.7.3 version of Randomloot

No matter what I have in the config settings, I always get the message not enough blaze powder in the off hand, despite having the exact amount (or more) of blaze powder in the off hand that is set in the config file.  Tried setting it to 0 and still get the same message.

Should add that it also does not work.  I am getting the message and cannot access the anvil.

**Comment by TheMarstonConnell** [comment]
I am unable to reproduce this in any version of the mod. Could you send me your config and a screen recording of the event. Send it to the discord linked on the main page thanks.

**Comment by Goldy93** [comment]
Will do.  May not happen for a couple of days, but will record quick clip and send it with the config.
Rich Harris

    On Saturday, March 28, 2020, 4:14:27 PM CDT, Marston Connell <notifications@github.com> wrote:  
 
 


I am unable to reproduce this in any version of the mod. Could you send me your config and a screen recording of the event. Send it to the discord linked on the main page thanks.
