### ISSUE TITLE
Error when adding trait

### ISSUE THREAD

**Issue by Goldy93** [TheMarstonConnell/randomlootmod#33]
When trying to add or remove a trait, nothing happens and get the following error in the console.  This is on a server and I am op on it.

This was on a pair of Titanium Runners that had no traits.  I entered "/trait add regenerating"

24.02 09:47:07 [Server] Server thread/ERROR [FML]: FMLIndexedMessageCodec exception caught
24.02 09:47:07 [Server] INFO java.lang.RuntimeException: Missing
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:299) ~[FMLServerHandler.class:?]
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:555) ~[FMLCommonHandler.class:?]
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$10.selectNetworks(FMLOutboundHandler.java:329) ~[FMLOutboundHandler$OutboundTarget$10.class:?]
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:?]
24.02 09:47:07 [Server] INFO at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:321) [SimpleNetworkWrapper.class:?]
24.02 09:47:07 [Server] INFO at com.mic.randomloot.util.handlers.NetworkHandler.addTrait(NetworkHandler.java:26) [NetworkHandler.class:?]
24.02 09:47:07 [Server] INFO at com.mic.randomloot.commands.AddTraitCommand.func_184881_a(AddTraitCommand.java:76) [AddTraitCommand.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
24.02 09:47:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
24.02 09:47:07 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_162]
24.02 09:47:07 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
24.02 09:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
24.02 09:47:07 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
24.02 09:47:07 [Server] INFO Feb 24, 2020 9:47:07 AM io.netty.channel.embedded.EmbeddedChannel recordException
24.02 09:47:07 [Server] INFO WARNING: More than one exception was raised. Will report only the first one and log others.
24.02 09:47:07 [Server] INFO java.lang.RuntimeException: Missing
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:299)
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:555)
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$10.selectNetworks(FMLOutboundHandler.java:329)
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
24.02 09:47:07 [Server] INFO at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
24.02 09:47:07 [Server] INFO at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
24.02 09:47:07 [Server] INFO at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
24.02 09:47:07 [Server] INFO at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
24.02 09:47:07 [Server] INFO at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:321)
24.02 09:47:07 [Server] INFO at com.mic.randomloot.util.handlers.NetworkHandler.addTrait(NetworkHandler.java:26)
24.02 09:47:07 [Server] INFO at com.mic.randomloot.commands.AddTraitCommand.func_184881_a(AddTraitCommand.java:76)
24.02 09:47:07 [Server] INFO at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119)
24.02 09:47:07 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91)
24.02 09:47:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
24.02 09:47:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
24.02 09:47:07 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
24.02 09:47:07 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
24.02 09:47:07 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
24.02 09:47:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
24.02 09:47:07 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source)
24.02 09:47:07 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46)
24.02 09:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
24.02 09:47:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
24.02 09:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
24.02 09:47:07 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
24.02 09:47:07 [Server] INFO at java.lang.Thread.run(Unknown Source)

**Comment by TheMarstonConnell** [comment]
Fixed in 1.7.4
