### ISSUE TITLE
Insightful (Night Vision) Buff Flickers Screen

### ISSUE THREAD

**Issue by TheVisionaryOne** [TheMarstonConnell/randomlootmod#34]
When wearing a piece of armor with the Insightful buff (and probably when holding gear with the buff), my entire screen flickers because of the Night Vision "wearing off" effect. It's really, really aggravating and hurts to watch for extended periods of time, almost making it not worth using any gear that has the buff.

There _is_ another mod called NoNightVisionFlicker or something similar, but that one crashes my game due to an incompatibility with another mod.

Either way, it should be a relatively easy problem to fix, just by changing the amount of seconds a player has the night vision effect for when they have the Insightful buff. Shouldn't make any difference gameplay-wise, since the effect isn't supposed to run out while the player has the item in their hand anyways.

**Comment by TheMarstonConnell** [comment]
Which version are you on?

**Comment by TheVisionaryOne** [comment]
The newest one as of right now. Version 1.7.4.
