### ISSUE TITLE
3 golden anvils bug

### ISSUE THREAD

**Issue by AlyaqdhanZ** [TheMarstonConnell/randomlootmod#36]
theres 3 golden anvils (2 dupelicated without textures)
![Annotation 2020-05-11 002848](https://user-images.githubusercontent.com/58079015/81509842-8a7d7080-931e-11ea-9618-72dc8f6a4b3b.jpg)
fix please :)

**Comment by TheMarstonConnell** [comment]
I have no idea what causes this and quite honestly it isnt bothering anyone by being in the creative menu, so this is just something I won't fix. Sorry

**Comment by AlyaqdhanZ** [comment]
Totally true it doesn't bother anyone in the creative menu, but what about jei (just enough items)?
I can't hide it because they're all like 1 item, when i try to hide them they all get selected (with the one that have texture).
soo please can you search more what causes this it means alot if you fixed it, thanks :)

By the way your mod is amazing when is the boomrang texture will be added?
Also can you make the new loot case shards glow like they're enchanted? I think they will be cooler?

**Comment by TheMarstonConnell** [comment]
As for the jei interface, I just don't see it being a huge issue to spend
hours fixing it. As for the glowing textures that sounds cool and I'll look
into it, and finally the boomerang is in the game already, maybe update to
the newest version, it's fairly rare though.

**Comment by AlyaqdhanZ** [comment]
Yes I've got the boomerang and tried it but I think it doesn't have animation for throwing, it throws something weird (like grey block), is that missing texture or what?
It applies to all throwing things, can you make animation for them?

**Comment by TheMarstonConnell** [comment]
Oh yeah all throwables have the same texture when thrown, it is something I
literally cannot change because of how Minecraft is programmed.

**Comment by AlyaqdhanZ** [comment]
There is boomerang called 'Pickarang' in mod quark that actually works, Idk how they made it.

**Comment by TheMarstonConnell** [comment]
It is possible to do that but I would have to rework the throwables
entirely and create a seperate item for each throwables which would create
like 8 new files in the mod and add a bunch of item renderers. Overall it's
just impossible to implement with my mod, other mods can but the way mine
is set up means I can't do that.

**Comment by AlyaqdhanZ** [comment]
Thats unfortunate, anyways thank you for listening to me.
