### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by migmolrod** [TheMarstonConnell/randomlootmod#4]
Is there any documentation or wiki planned to give players more information?
For example, what does each "modifier" do in tools/weapons? Some of them are pretty self-explanatory, others don't (I'm specially interested on what Filling does in pickaxes)

**Comment by TheMarstonConnell** [comment]
There will be soon, filling also randomly fills your hunger bar by half a drumstick when you break blocks.

**Comment by TheMarstonConnell** [comment]
Okay A quick wiki is done.
