### ISSUE TITLE
[1.12.2 mod ver 1.7.4] Insightful attribute's given night vision has a low duration causing visual glitches

### ISSUE THREAD

**Issue by GodOfWar104** [TheMarstonConnell/randomlootmod#44]
Hi, thanks for making this great mod with so many different combinations of items sets and what not! This is the only small problem i noticed that, as you probably know, the potion effect of night vision starts blinking the screen when the potion effect is at its end, and so the mod has set it at a constant 5 seconds it seems that it's the threshold when this signal of the ending effect start, causing an extremely fast blinking effect as if the night vision goes on and off.

**Comment by Zedrimar** [comment]
That's a minecraft thing, not a glitch, but I think that one can possibly be made as a permanent affect as long as armor is applied. Not sure how easy it would be to actually code for armor though, but I have seen it done in the rings of ascension mod

**Comment by GodOfWar104** [comment]
My suggestion is just to make potion effects 15 seconds as to avoid other such glitches

**Comment by Zedrimar** [comment]
Understandable :P

**Comment by TheMarstonConnell** [comment]
No longer updating 1.12.2 please update
