### ISSUE TITLE
Minecraft crashes because of forge 1.16 breaking how commands should work

### ISSUE THREAD

**Issue by Dennias** [TheMarstonConnell/randomlootmod#47]
when i open the minecraft , everything is fine but then i create new world and it crashes instantly.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 22.7.2020 9:44
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
	at xyz.marstonconnell.randomloot.RandomLootMod.onServerStarting(RandomLootMod.java:122) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_50_RandomLootMod_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:65) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5671/428156140.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1350657280 bytes (1288 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.75.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.75
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.75-client.jar Minecraft {minecraft@1.16.1 DONE}
		useful_backpacks-1.16.1-1.11.1.69-SNAPSHOT.jar Useful Backpacks {usefulbackpacks@1.11.1.69-SNAPSHOT DONE}
		RandomLoot2.0.jar Random Loot Mod {randomloot@1.0 DONE}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 DONE}
		Bookshelf-1.16.1-6.1.11.jar Bookshelf {bookshelf@6.1.11 DONE}
		u_team_core-1.16.1-3.1.1.163-SNAPSHOT.jar U Team Core {uteamcore@3.1.1.163-SNAPSHOT DONE}
		starterkit_1.16-1.0.jar Starter Kit {starterkit@1.0 DONE}
		ironfurnaces-1.16.1-2.1.1.jar Iron Furnaces {ironfurnaces@2.1.1 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		Ma-Essentials-1.16.1-3.2.3.jar Ma Essentials {maessentials@1.16.1-3.2.3 DONE}
		ExpOreMod-1.16.1-1.0.jar Exp Ore Block {exp_ore@1.0 DONE}
		forge-1.16.1-32.0.75-universal.jar Forge {forge@32.0.75 DONE}
		infinitetrading_1.16-1.1.jar Infinite Trading {infinitetrading@1.1 DONE}
		RingsOfAscension-1.16.1-1.5.2.jar Rings of Ascension {ringsofascension@1.5.2 DONE}
		curios-FORGE-1.16.1-3.0.jar Curios API {curios@FORGE-1.16.1-3.0 DONE}
		SimpleOres2-1.16.1-2.2.0.1.jar Simple Ores {simpleores@1.16.1-2.2.0.1 DONE}
		gravestone-1.16.1-1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 DONE}
		OAD1.16Alpha.jar Ores Above Diamonds {oresabovediamonds@4.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:usefulbackpacks, mod:randomloot, mod:ma-enchants (incompatible), mod:bookshelf (incompatible), mod:uteamcore, mod:starterkit, mod:ironfurnaces (incompatible), mod:dungeons_plus, mod:jei (incompatible), mod:maessentials (incompatible), mod:exp_ore, mod:forge, mod:infinitetrading, mod:ringsofascension, mod:curios (incompatible), mod:simpleores, mod:gravestone, mod:collective, mod:structure_gel, mod:oresabovediamonds (incompatible), mod:ironchest, mod:storagedrawers (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Zedrimar** [comment]
Update your randomloot mod version, that was already fixed :P

(pretty much every mod broke with that one due to some changes forge implemented without telling)

**Comment by Dennias** [comment]
I see , didnt even notice. Thank you a lot

**Comment by Zedrimar** [comment]
> I see , didnt even notice. Thank you a lot

No worries, just be sure to close this issue when you can confirm it fixes :)

**Comment by Dennias** [comment]
Yes its working now. Thanks a lot

**Comment by Zedrimar** [comment]
You're welcome :3
