### ISSUE TITLE
[1.16.1] Armor With Fortified Gain No XP

### ISSUE THREAD

**Issue by Zedrimar** [TheMarstonConnell/randomlootmod#48]
Mod: 2.1.4
Forge: *.75

I have leggings that are unbreakable but get no xp afterward for some reason. Seems like it counts by damage ticks possibly?

**Comment by TheMarstonConnell** [comment]
You're 100% right, I'll try and fix that

**Comment by Zedrimar** [comment]
Oh cool, I actually guessed right! Good luck on that one :P

**Comment by Zedrimar** [comment]
I have an idea.... Obviously for just about everything else like tools, it's a good thing to not have it have damage ticks (since it just counts by blocks broken anyway), but I think fortified on armor can have it where it will take the tick but insta repair itself for armor. I saw a mod called forbidden and arcanus that has an indestructible enchantment that works that way, it would probably do well with armor. You'd just have to be sure that even if it reaches to 0 it won't break. Though I think an easy work around is just to make the amount of durability it has to just be some ridiculous value that only 1000 withers firing at once could ever destroy. Not sure if it'll work, but maybe worth a shot!

**Comment by TheMarstonConnell** [comment]
Fixed in 2.1.8!
