### ISSUE TITLE
[1.16.1] Armor stands drop loot bags

### ISSUE THREAD

**Issue by CuchilloMucho** [TheMarstonConnell/randomlootmod#49]
Title basically, seems a bit OP

**Comment by TheMarstonConnell** [comment]
Which mod version?

**Comment by CuchilloMucho** [comment]
Oh sorry I didnt look if there was an update but the version was 2.1.4

**Comment by darkphan** [comment]
This happens in version 2.1.5 as well.

**Comment by TheMarstonConnell** [comment]
Should be fixed in the newest release.
