### ISSUE TITLE
tiers of the cases not affecting tiers of the gear you get

### ISSUE THREAD

**Issue by jinkhya** [TheMarstonConnell/randomlootmod#5]
Hello!
I opened a few bags of each kind and it seems like all the bags can give you all gear. Like a basic bag can give you purple gear and purple bag can give you basic gear. 

Forge : 2768
randomloot : 1.4

Thanks in advance !

**Comment by TheMarstonConnell** [comment]
It is meant to be that way, the cases affect the chance of which items you get but don't immediately affect them.

**Comment by jinkhya** [comment]
Aww, i wanted to add different loot cases tiers to different loot chests to gate the better weapons in harder dungeons. I'm guessing there's no way you could add a config to restrict loot tiers to the bags?

**Comment by TheMarstonConnell** [comment]
I could work on that soon.

**Comment by jinkhya** [comment]
that'd be highly appreciated ! :D
