### ISSUE TITLE
Weapons getting no XP

### ISSUE THREAD

**Issue by yancypro** [TheMarstonConnell/randomlootmod#51]
Downloaded 1.16.1-2.1.5.jar and when using mod tools / weapons, they gain no XP. As you can see by the picture I have attached, I have used the different items (green bar not full) but the XP says 0. Please fix.
Also, could not find a CONFIG file for this mod, maybe that's the reason?  Also, no in-game guide or book?

Other than that, love the mod. Hope it keeps getting better!
![Minecraft_1 16 1_Random_Loot_Mod_Pic_20200802](https://user-images.githubusercontent.com/65453692/89126206-ef75dc00-d4b1-11ea-9ef1-7d97451cb883.JPG)

Thanks, Yancy P.

**Comment by TheMarstonConnell** [comment]
Delete the config in the "config" folder. Just google changing config and it'll walk you through it.

**Comment by yancypro** [comment]
I asked Google and it gave me a bunch of garbage I don't understand. Could
you explain what you mean a little more on your statement? There is No
Config file for RandomLoot but maybe you mean the Main Minecraft Config
file??

**Comment by TheMarstonConnell** [comment]
There is a config file for randomloot. If you installed Minecraft forge
without any sort of launcher the folder will be %appdata%/.minecraft/config
and inside will be the config otherwise just find the config folder in your
Minecraft install folder
