### ISSUE TITLE
1.12 Damage++ heals mobs

### ISSUE THREAD

**Issue by darchitectlp** [TheMarstonConnell/randomlootmod#52]
For whatever reason, the damage++ is actually healing undead mobs. Either change the effect so that it actually damages them, as the user would expect, or add a description/rename the enchant to clearly identify what it's mechanic is. Took me forever to figure out what was going on and narrow it down to your mod. Discovered this playing the RAD modpack.

Love the mod, though! Thanks for your hard work!

**Comment by TheMarstonConnell** [comment]
1.12 is no longer supported sorry.
