### ISSUE TITLE
Damage+ and Damage++ healing the mob.

### ISSUE THREAD

**Issue by Isaakk** [TheMarstonConnell/randomlootmod#57]
When I attack a mob with Damage+ or Damage++ it seems to give a buff to that mob, making it healing thus imposible to kill.

Edit: Guess it's an incompatibility with another mod, but this mod (Random loot mod) it's better with more mods, so would be good to check it, for example an Sword with the Damage++ trait will heal Primitive Mobs/Grimoire of Gaia 3 mobs.

Version 1.7.4

**Comment by TheMarstonConnell** [comment]
Damage ++ is renamed in the newest release. It works as intended.
