### ISSUE TITLE
Language naming conflicts

### ISSUE THREAD

**Issue by TartaricAcid** [TheMarstonConnell/randomlootmod#6]
Random loot mod's I18n don't have namespace, and have some conflicts with minecraft
> `item.bow.name`
> - **randomloot**: `Random Bow`
> - **minecraft**: `Bow`

I think the forge doc can help your: https://mcforge.readthedocs.io/en/latest/concepts/internationalization/#usage-with-blocks-and-items

Unlike registry names, translation keys are not namespaced. It is therefore highly recommended to prefix your modid somewhere to the translation key (e.g. examplemod.example_item) to avoid naming conflicts. Otherwise, in the event of a conflict, the localization of one object will override the other.

**Comment by TheMarstonConnell** [comment]
Fixed in 1.4.4
