### ISSUE TITLE
Generic Random items are craftable

### ISSUE THREAD

**Issue by naruheme** [TheMarstonConnell/randomlootmod#60]
1.16.3 allows you to craft Random Sword/Axe/Bow/etc
These items look normal but require 0 exp to level up and eventually this
![image](https://user-images.githubusercontent.com/54568579/95684384-5c4ad800-0bbf-11eb-9752-883c2ac8f6bf.png)
 is possible

**Comment by TheMarstonConnell** [comment]
Fixed in 2.1.8
