### ISSUE TITLE
This doesn't work with Tree Harvester

### ISSUE THREAD

**Issue by DatrixTHLK** [TheMarstonConnell/randomlootmod#62]
Hi,

It appears that when I use the axes that come from the random loot boxes, they don't work along side the [Tree Harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester) mod. When chopping a tree the logs above it don't break.

Minecraft: 1.16.3
Forge: 34.1.22/3
Collective: 1.51
Random Loot: 2.1.7
Tree Harvester: 1.7

I will put this in Tree Harvesters mod issue list as well incas it is on his end

**Comment by ricksouth** [comment]
I'm checking for the ToolType.Axe property to determine if the player is holding an axe:

ItemStack mainheld = player.getHeldItem(Hand.MAIN_HAND);
if (!mainheld.getToolTypes().contains(ToolType.AXE)) {
	return;
}

I think adding those to your custom tools will do the trick.

**Comment by TheMarstonConnell** [comment]
Fixed in 2.1.8

**Comment by DatrixTHLK** [comment]
Thanks! Appreciate the response back.
