### ISSUE TITLE
[1.16.3] Mobs killed with RL weapons aren't dropping drops

### ISSUE THREAD

**Issue by lulabyte** [TheMarstonConnell/randomlootmod#63]
Hello! We love the mod on the server, just recently upgraded to 1.16.3 and one of my players is saying that when he kills things with the sword he got from the Random Loot bag, the MOBS aren't dropping drops. I haven't yet tested this myself, I'm about to. But I thought I'd start the issue up.

Thank you for the mod and all your work!

**Comment by legendsarising** [comment]
I am having the same problems with our smp server. Only thing we have found is it happens once infinity edge is added to the weapon.

**Comment by TheMarstonConnell** [comment]
Fixed in 2.1.8
