### ISSUE TITLE
Unable to repair 1.16.3

### ISSUE THREAD

**Issue by legendsarising** [TheMarstonConnell/randomlootmod#66]
In the newer versions you are unable to repair the tools and items with a random cluster and an anvil.

**Comment by lulabyte** [comment]
Second, using 1.16.3 and I simply get no output when I put the loot mod weapon in the anvil with a random cluster.

Thanks for the mod! It's a lot of fun.

**Comment by themonsterstorm** [comment]
also having this issue

**Comment by TheMarstonConnell** [comment]
Fixed in version 2.1.8
