### ISSUE TITLE
Mining speed on pickaxe copy themselves if you swap them in hotbar.

### ISSUE THREAD

**Issue by jinkhya** [TheMarstonConnell/randomlootmod#7]
Hello !

Just found an issue with pickaxes : 

Forge : 2765
randomloot : 1.4.1

Steps to reproduce : 
- Equip a pickaxe in slot 1 with mining speed 10 for example and another one in slot 2 with mining speed 19 in second one. 
- use the pickaxe in slot one and then swap the two pickaxes between slot 1 and 2 and use that one. 
- at some point the pickaxes will have same mining speed. (either 10 or 19 in my example)

Also I wanted to say thank you SO MUCH for the config to bind tiers to the boxes. :D literally made my day.

**Comment by TheMarstonConnell** [comment]
Solved in 1.13 version. Currently in alpha.
