### ISSUE TITLE
[1.16.5] Axe generate error and can't break block

### ISSUE THREAD

**Issue by WareZ57** [TheMarstonConnell/randomlootmod#74]
Hello,

I am coming to you following the discovery of a bug on two axes.

This generates errors in the console and does not break the block (become invisible to the person who breaks it but not other players)

Short vid: https://streamable.com/xvhqtx
Console Error : https://i.imgur.com/vt9uWwG.png

Axe bugs : 

https://i.imgur.com/jb2Svj8.png
https://i.imgur.com/39MtKRw.png

Thanks you.

**Comment by TheMarstonConnell** [comment]
Should be fixed in 2.3.8
