### ISSUE TITLE
Wiki commands are wrong.

### ISSUE THREAD

**Issue by mhmyesman** [TheMarstonConnell/randomlootmod#76]
Wiki commands are incorrect and don't correspond to the actual commands needed to add or remove traits. 

Ex: 
To remove a trait from a piece of armor, you need to use `/trait remove <trait>`
The wiki currently states the command is `/deltrait  <trait>`

**Comment by TheMarstonConnell** [comment]
You're using the old version of the mod, nothing is wrong with the wiki.
