### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Lordbaane** [TheMarstonConnell/randomlootmod#8]
The weapon on an Overlord minion caused a null crash:

https://paste.dimdev.org/oqahulakeb.mccrash

**Comment by TheMarstonConnell** [comment]
What effects did the weapon have on it?

**Comment by Lordbaane** [comment]
It killed the creature, but I believe during the pickup of the items dropped it caused a crash. I attempted to restart the world and once it attacked another monster it crashed once more.

**Comment by Lordbaane** [comment]
The weapon was as is, no modifications.

**Comment by TheMarstonConnell** [comment]
My mod adds modifiers to weapons, like "starving" or "poisonous" which of these were on the weapon?

**Comment by Lordbaane** [comment]
Might have been one of those on it, not sure as I wasn't able to keep the world active to check.

**Comment by TheMarstonConnell** [comment]
I can't do a whole lot with just the crash log, I assume it's something from the other mod not liking what I'm doing to entities, so I can check but I can't guarantee a fix.

**Comment by Lordbaane** [comment]
I'm sure it will come up again at some point. For now you can close this until it does.
