### ISSUE TITLE
Shot arrows can be picked up as "Uncraftable Tipped Arrow"

### ISSUE THREAD

**Issue by DGSitze** [TheMarstonConnell/randomlootmod#9]
Title. shoot an arrow with a bow that gives status effects, run over and pick the arrow up to retrieve an uncraftable tipped arrow instead of a normal arrow. this wouldn't be so much of a problem if they didn't take up a lot of room... especially when finding new/better bows all the time.

**Comment by sporefreak** [comment]
on a side note. Spectral arrows do not apply the glowing effect. I'm assuming this is because of the same reason the posted bug happens. (Unless you are trying to spam peoples inventories with uncraftable arrows)

**Comment by TheMarstonConnell** [comment]
Fixed in 1.4.4 - arrows can no longer be picked up at all until I find better option.
